_Roadmap_
 introduction Data with Python => Applied Plotting, Charting & Data Representation in Python,Applied Machine Learning in Python,Applied Text Mining in Python, Applied Social Network Analysis in Python.

In [ ]:
x = (1,'a',2,'b')
type(x)


tuple

isso significa que uma tupla tem itens em uma ordem e não pode ser alterada depois de criada.
Codificamos tuplas usando parênteses, podemos misturar tipo de conteúdos da tupla.
Aqui está uma tupla que tem quatro itens, dois números e dois são sequências de caracteres. Observe aqui que uso aspas simples para uma sequência de caracteres, enquanto que, anteriormente, eu usei aspas duplas.
Em Python, tanto aspas simples quanto duplas podem ser usadas para denotar strings. Listas são muito semelhantes, mas elas podem ser mutáveis, então você pode alterar o seu comprimento, número de elementos e os valores dos elementos. Uma lista é declarada usando colchetes. Há algumas maneiras de mudar o conteúdo de uma lista Uma é através da função "append" (acrescentar), que lhe permite acrescentar novos itens ao final da lista. Ambos, listas e tuplas são tipos iteráveis.
Então, você pode gravar loops para passar por cada valor que elas detêm. A norma, se você quiser examinar cada item em uma lista, é usar um comando "for". Isso é semelhante ao "for-each" loop em linguagens como Java e C#, note que a tipagem não é necessária.
Listas e tuplas também podem ser acessadas assim como "arrays" (matrizes) podem em outras linguagens, usando o operador colchete, que é chamado o operador de indexação. O primeiro item da lista começa na posição zero e para obter o comprimento da lista, nós usamos a função interna "len". Existem algumas outras funções comuns que você pode esperar como "min" e "max", que encontrarão os valores máximos ou mínimos em uma determinada lista ou tupla. Listas e tuplas em Python também têm algumas operações matemáticas básicas que podem ser permitidas neles. O sinal de adição concatena listas, por exemplo, e o asterisco, repete os valores de uma lista.
Um operador muito comum, é o operador "in". Isto pesquisa um conjunto e retorna um valor booleano "true" (verdadeiro) ou "false" (falso) dependendo se um item está em uma determinada lista. Vamos mergulhar mais em operadores e em tipos especiais de sequências numa semana mais adiante, quando estudaremos uma técnica chamada "broadcasting" (transmissão). Talvez, as operações mais interessantes que você pode usar com listas são chamadas de "slicing" (corte/fatiamento). Enquanto o colchete, a sintaxe de matriz para acessar um elemento pode parecer bastante semelhante ao que você já viu em outras linguagens, Em Python, o operador de indexação te permite manipular múltiplos valores. O primeiro parâmetro é a localização inicial. Se este é o único elemento, então um item é retornado a partir da lista. O segundo parâmetro é o fim da fatia e é um fim exclusivo. Então, se você já cortou com o primeiro parâmetro a ser zero, o próximo parâmetro sendo um, então você só obterá um item. Isso é muito mais fácil de ser explicado com um exemplo. Um aspecto prático do Python, é que todas as "strings" são na verdade apenas listas de caracteres. Então, o corte funciona maravilhosamente neles. Aqui está um exemplo. Quando rodamos "x[0]" ou "x[0 : 1]", temos apenas o primeiro caractere da sequência de caracteres. Mas, quando rodamos "x[0 : 2]", temos os dois primeiros caracteres da sequência de caracteres. Nossos valores de indexação também podem ser negativos, o que é realmente legal. Isto significa para indexar a partir do final da sequência de caracteres. Então, "x[-1]", nos dá a última letra da sequência de caracteres. E "x[-4 : -2]", lê-se em todos os caracteres da quarta última até a penúltima posição. Finalmente, se quisermos fazer referência ao início ou fim da sequência de caracteres, implicitamente, basta apenas deixar o parâmetro vazio. Então, "x[ : 3]", começa com o primeiro caractere e vai até a posição três, e um "x[3 : ]" começa no quarto caractere, porque indexação sempre começa com zero, e vai até o final da lista. "Slicing" é o núcleo da linguagem Python e é uma grande parte da computação científica em Python também, especialmente se você começar a manipular matrizes. Vamos falar mais sobre "slicing" no próximo módulo, Mas aqui vai uma pergunta para você começar. Eu estou desviando um pouco falando sobre manipular strings. "Slicing" não é a única maneira de manipular sequências de caracteres, e uma atividade comum é dividir as sequências de caracteres ("strings") com base em "substrings" (subsequências). Ou seja, passar a sequência de caracteres à procura de padrões e segmentando-a como apropriado. Isso é chamado de avaliação de expressão regular. Veremos isto detalhadamente na seção da especialização, que lida com a mineração de texto, uma vez que é uma operação muito comum. Mas, Python tem algumas ferramentas básicas para análise de texto, que lhes mostrarei aqui. Como vimos, strings são apenas listas de caracteres. Então, as operações que você pode fazer em uma lista, você pode fazer numa string. Isto significa que você pode concatenar duas strings usando o operador de adição (+), e multiplicando-se strings irá repetir uma determinada sequência de caracteres. Você também pode procurar por strings usando o operador "in". O tipo string tem uma função associada chamada "split". Essa função separa a string em sub-strings de acordo com um padrão simples Aqui por exemplo, vou dividir meu nome completo baseado na presença de um caractere de espaço, o resultado é uma lista de quatro elementos. Podemos escolher o primeiro elemento com o operador de indexação para ser o primeiro nome e o último elemento a ser o meu último nome. Vou tocar nas strings um pouco mais, mas antes quero falar sobre dicionários. Dicionários são semelhantes às listas e tuplas, em que eles guardam uma coleção de itens. Mas, eles são coleções rotuladas, que não têm uma ordenação. Isto significa que para cada valor que inserir no dicionário, você também deve dar uma chave para receber o valor de volta. Em outras línguas, a estrutura é frequentemente chamada de mapa, e em Python, usamos as chaves para denotar um dicionário. Aqui está um exemplo, onde podemos vincular nomes para endereços de e-mail. Você pode ver que indicamos cada item do dicionário ao criá-lo usando um par de valores separados por dois pontos, que você pode recuperar um valor para um determinado rótulo usando o operador de indexação. Os tipos que você usar para índices ou valores no dicionário podem ser qualquer coisa e isso pode ser uma mistura de tipos, se preferir. Podemos adicionar novos itens ao dicionário usando o mesmo operador de indexação que estamos acostumados, do lado esquerdo de uma instrução. Você pode iterar sobre todos os itens em um dicionário em um número de maneiras. Primeiro, você pode iterar sobre todas as chaves e só retirar o conteúdo como quiser, ou você pode iterar sobre os valores e só ignorar as chaves. Finalmente, você pode iterar sobre ambos os valores e as chaves de uma vez, usando a função do item.
Reproduza o vídeo começando em :7:38 e siga a transcrição7:38
Este último exemplo, é um pouco diferente e é um exemplo de algo chamado de descompactação. Em Python, você pode ter uma sequência. É uma lista ou uma tupla de valores e você pode descompactar esses itens em diferentes variáveis através de atribuição em um comando. Aqui está outro exemplo de que, onde temos uma tupla que tem meu nome, meu sobrenome e o meu e-mail..

In [ ]:
#ex lista
x=[1,'a',2,'b']
type(x)
x.append(3.3)
print(x)

[1, 'a', 2, 'b', 3.3]


In [ ]:
for item in x:
    print(item)

1
a
2
b
3.3


In [ ]:
i = 0
while(i != len(x) ):
    print(x[i])
    i = i+1

1
a
2
b
3.3


In [ ]:
x = 'This is a string'
print(x[0])
print(x[0:1])
print(x[0:2])

T
T
Th


In [ ]:
firstname = 'Vinicius'
lastname= 'Silva'
print(firstname+' '+lastname)

Vinicius Silva


Manipulação de strings com python


In [ ]:
sales_record ={'price': 3.24,
               'num_items': 4,
               'person':    'Vinicius'}
sales_statement = '{} bought {} item(s) at price of {} each for total of {}'
print(sales_statement.format(sales_record['person'],
                             sales_record['num_items'],
                             sales_record['price'],
                             sales_record['num_items']*sales_record['price']))

Vinicius bought 4 item(s) at price of 3.24 each for total of 12.96


Lendo e Escrevndo Arquivos CSV
é possível ver o nome das colunas do CSV usando o método Key.

In [ ]:
import csv

%precision 2

with open('mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))

mpg[:3]

FileNotFoundError: ignored

In [ ]:
len(mpg)
mpg[0].keys()

Dates and Times:
exemplo de utilidade, encontrar número de vendas de um certo período. Selecionar uma lista de produtos para prospectar dados, se eles foram adquiridos em um dado período.
para criar uma marca temporal pode se utilizar  a função "fromtimestamp", no objeto "datatime"


In [ ]:
import  datetime as dt
import time as tm
tm.time()
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second


(2023, 4, 20, 9, 29, 46)

Objects e Map()

In [ ]:
class Person:
    departament = 'School of Information'

    def set_name(self,new_name):
        self.name = new_name
    def set_location(self,new_location):
        self.location = new_location

In [ ]:
store1  =   [10.00,    11.00,  12.34,  2.34]
store2  =   [9.00,  11.10,  12.34,  2.01]
mais_barato    =   map[min,store1, store2]
mais_barato

TypeError: 'type' object is not subscriptable

Lambda e Lista de Compreensões

A sintaxe lambda é relativamente simples. Mas talvez leve algum tempo para se acostumar a usa-lá.
Você declara a função lambda com a palavra lambda, seguida por uma lista de argumentos, seguidos por dois-pontos (:) e então uma única expressão e isto é chave. Existe apenas uma expressão para ser avaliada em uma função lambda. O valor da expressão é retornado na execução da lambda.
O retorno de uma lambda é uma referência de função. Então, neste caso, você deve executar "my_function" e passar três parâmetros diferentes.
Observe que você não pode ter valores padrão para parâmetros de lambda e você não pode ter lógica complexa dentro da lambda em si, porque você está limitado a uma única expressão.
Então as lambdas são realmente muito mais limitadas do que as definições de uma função completa. Mas eu acho que elas são muito úteis para pequenas tarefas de limpeza de dados. E você verá muitos exemplos com elas na internet. Então você deve ser capaz de ler e escrever lambdas. Vamos fazer uma tentativa aqui.
Aprendemos muito sobre sequências em Python. Tuplas, listas, dicionários e assim por diante.
As sequências são estruturas que podemos iterar, e muitas vezes as criamos através de loops ou lendo dados de um arquivo.
Python tem suporte embutido para criar essas coleções usando uma forma mais abreviada de sintaxe chamada compreensão de lista.

NumPy

NumPy é uma das bibliotecas essenciais para computação numérica com Python. Ela fornece poderosas maneiras para criar, armazenar e manipular dados, podendo ser, de maneira coerente e rápida, associada a uma ampla variedade de bancos de dados e formatos. Ela também é a base da qual a Pandas foi construída, que é uma biblioteca de alto desempenho com foco nos dados, que nós veremos melhor, ao longo deste curso. Nesta aula, discutiremos sobre a criação de Arrays com certos tipos de dados, como manipulá-los, como selecionar seus itens e armazenar conjuntos de dados neles. Tais funções são úteis para manipulação de dados e para compreender as funcionalidades de outros pacotes comuns para dados do Python. Você deve se lembrar de que importamos uma biblioteca utilizando o comando import e a abreviatura mais comum para NumPy é np. Importaremos a NumPy como np e, também, a math.

You´ll recal that we import a library using the 'import' keyword as numpy´s common abbreviation is np

In [ ]:
import numpy as np
import math

# Array Creation

In [ ]:
#Arrays are displayed as list or lists of lists can be through lists as well. When creating an array, we pass in a list as an argument in numpy array
a = np.array([1,2,3])
print(a)
print(a.ndim)

#if we pass in a list of lists in numpy array, we create a multi dimensional array, for instance, a matrix
b = np.array([[1,2,3],[4,5,6]])
b

[1 2 3]
1


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#we can print out length of each dimension by calling the shape attribute, which returns a tuple
b.shape

(2, 3)

In [ ]:
#we can also check the type of items in the array
a.dtype

dtype('int64')

In [ ]:
#Besides integers, floats are also accepted in numpy arrays
c = np.array([2.2,5,1.1])
c.dtype.name

'float64'

In [ ]:
d = np.zeros((2,3))
print(d)

e = np.ones((2,3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#we can also generate an array with an array random numbers
np.random.rand(2,3)

array([[0.61, 0.36, 0.2 ],
       [0.9 , 0.97, 0.21]])

In [ ]:
#you´ll see zeros, ones, and rand used quite often to create example arrays, especially in stack overflow posts and other forums.
#we can also create a sequence os numbers in arrays with the arrange() function. The first argument is the starting bound the second argument is the ending bound, and the thrid argument is the difference between each consecutive numbers
#let´s create an array of every number from(inclusive) to fifty (exclusive)
f = np.arange(10,50,2)
f


array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [ ]:
#Se quisermos gerar uma sequência de floats, usamos algo chamado linspace(). Nesta função, o terceiro argumento não é a diferença entre os dois números,
#mas é o número total de itens que você deseja gerar. Se você quiser isso, então:
np.linspace(0,2,15)#15 numbers from 0 (inclusive) to 2(inclusive)

array([0.  , 0.14, 0.29, 0.43, 0.57, 0.71, 0.86, 1.  , 1.14, 1.29, 1.43,
       1.57, 1.71, 1.86, 2.  ])

**Array Operations**

In [ ]:
#pode ser feita muitas coisas com arrays, como manipulação matemática (adição, subtração, raiz)
#bem como os Arrays booleanos, apenas com valores binários. E também podemos fazer manipulações matriciais, como transposição, produto, inversão e e assim por diante.
#Então, vamos ver como alguns destes operadores aritméticos em Arrays se aplicam a cada elemento. Então, vamos criar alguns Arrays.
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])
#agora vamos ver a menos b
c = a-b
print(c)
d = a*b
print(d)

[ 9 18 27 36]
[ 10  40  90 160]


In [ ]:
#Então, aqui está um problema do mundo real que eu enfrentei. Eu me mudei para os Estados Unidos há cerca de seis anos, vindo do Canadá.
#Lá no Canadá, usamos Celsius para temperaturas e minha esposa ainda não se acostumou com o sistema dos EUA, que usa Fahrenheit.
#Com a NumPy eu poderia facilmente converter vários valores em Fahrenheit, digamos, a previsão do tempo, para Celsius.
#Então, vamos criar um Array com valores, em Fahrenheit, do inverno de Ann Arbor.
farenheit = np.array([0, -10, -5, -15, 0])
#E a fórmula para conversão é ((ºF-32)x5/9 = ºC)
celsius = (farenheit-32)*5/9
celsius

array([-17.77777778, -23.33333333, -20.55555556, -26.11111111,
       -17.77777778])

In [ ]:
#Outra útil e importante manipulação é o Array booleano. Podemos aplicar um operador em um Array para que seja retornado um Array Booleano para qualquer elemento no original
#que satisfaça a condição do operador. Por exemplo, se queremos obter um Array booleano para verificar os graus em Celsius que são maiores do que -20 graus, basta colocar:
celsius > -20
#Vamos a outro exemplo, nós poderíamos usar o operador do módulo para verificar se números no Array são pares. Assim,
celsius%2

array([0.22222222, 0.66666667, 1.44444444, 1.88888889, 0.22222222])

In [ ]:
#Vejamos como fazer o produto de matrizes. Se queremos obter o produto elemento a elemento, nós usamos o sinal asterisco.
#Fazendo A igual a np.array, criando um Array aqui e B igual a np.array, nós vamos criar outro. E, com print, veremos o produto, ( A * B ).
#Mas se quisermos fazer o produto de matrizes, nós usaremos o símbolo @, ao invés do asterisco. Então os "*" são só para multiplicações "elemento a elemento";
#e isso é muito importante. Na verdade, os asteriscos são para os produtos “elemento a elemento” e você pode pensar no padrão como modificações e comparações deles,
#mas o sinal “@” é usado para os produtos de matrizes
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])
print(A*B)
print(A@B)

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


In [ ]:
#pode se usar numpy para ver o formato da matriz
A.shape

(2, 2)

In [ ]:
array1 = np.array([[1,2,3],[4,5,6]])
array2 = np.array([[7.1,8.2, 9.1],[10.4, 11.2, 12.3]])
array3 = array1+array2
print(array3)

[[ 8.1 10.2 12.1]
 [14.4 16.2 18.3]]


In [ ]:
print(array3.sum())
print(array3.max())
print(array3.min())
print(array3.mean())

79.3
18.3
8.1
13.216666666666667


In [ ]:
#Para Arrays bidimensionais, poderíamos fazer a mesma coisa para cada linha ou coluna. Criaremos então, um Array com 15 elementos que variam de 1 a 15,
#com a dimensão de 3 por 5.
#Então:
b = np.arrange(1, 16, 1).reshape(3, 5)
print(b)


AttributeError: ignored

In [ ]:
#Agora, muitas vezes, pensamos em Arrays com duas dimensões sendo constituídos por linhas e colunas, mas você, também, pode pensar nesses Arrays como uma lista grande de números ordenados e a
#forma (shape) dos Arrays. O número de linhas e colunas é apenas uma abstração que temos para um propósito particular.
#Na verdade, isso é exatamente como imagens normais são armazenadas em sistemas no computador.
#para esse exemplo será usada a biblioteca de imagem do python(PIL) e a função display
from PIL import image
from IPython.display import display

#E vamos dar uma olhada na imagem
im = Image.open('chris-tiff')
display(im)

ImportError: ignored

In [ ]:
#agora, podemos converter issa PIL image para a numpy array
array=np.array(im)
print (array.shape)
array


NameError: ignored

In [ ]:
#agora podemos ver que temos uma array 200X200 que corresponde ao valor uint8. O "uint" significa que eles são inteiros sem sinais, ou seja, que não há números negativos e o "8"
#significa 8 bits por byte. Isso significa que cada valor pode ir até o valor de dois elevado a 8 ou 256 no total. Mas, na verdade, é apenas 255, porque começamos em zero,
#como em toda a computação. Para imagens em preto e branco, o preto é armazenado como zero e o branco é armazenado como 255.
#Se quisermos apenas inverter as cores da imagem, podemos usar o Array do NumPy para fazer isso.
#vamos criar um array com a mesma forma
mask=np.full(array.shape,255)
mask

NameError: ignored

In [ ]:
#Agora podemos subtrair de uma array modificado
modified_array=array-mask
#E vamos converter todos of valores negativos para positivos
modified_array=modified_array*-1
#E por último
modified_array=modified_array.astype(np.uint8)
modified_array

NameError: ignored

**Indexing,Slicing and Iterating**
Então, a indexação, corte e iteração são extremamente importantes para manipulação e análise de dados. Porque essas técnicas nos permitem selecionar dados com base em condições e copiar ou atualizar os dados. Primeiro, vamos olhar para a indexação de inteiros, um Array unidimensional funciona de maneira semelhante a uma lista. Assim, para obter um elemento nesse array, nós apenas usamos um índice de distância.

In [ ]:
a= np.array([1,3,5,7])
a(2)

TypeError: ignored

In [ ]:
 #Para arrays multidimensionais, precisamos usar indexação de Arrays inteiros.
 a = np.array([[1,2],[3,4],[5,6]])
 a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
#Se quisermos selecionar um determinado elemento, podemos fazê-lo inserindo o índice, que é composto por dois inteiros.
#inteiros o primeiro sendo linha o segundo coluna
a[1,1] #lembrando que em python começa em 0


4

In [ ]:
#Se queremos obter vários elementos, por exemplo, ao colocar 1, 4 e 6 em um Array unidimensional, nós podemos inserir os índices diretamente na função do Array
np.array([a[0,0],a[1,1],a[2,1]])

array([1, 4, 6])

In [ ]:
#também podemos usar uma forma de indexação conhecida como zip
print(a[[0,1,2],[0,1,1]])

[1 4 6]


Já a indexação booleana nos permite selecionar elementos baseados em condições. Por exemplo, se na matriz que acabamos de falar, querermos encontrar elementos que são maiores que cinco, colocaremos uma condição: a > 5 E visualizaremos quais são maiores que cinco. Isso retorna uma matriz booleana mostrando os valores na célula correspondente que são maiores que cinco. Então temos aqui vários "Falsos" e vários "Verdadeiros". Assim, depois, podemos usar esse Array de valores booleanos como uma máscara sobre o Array original, para que seja visto um Array unidimensional com os valores que são verdadeiros. Portanto, se condicionarmos, a[a > 5], o que acontece é que este operador será aplicado em tudo, como veremos aqui. Para isso ele usará o operador em todos os elementos de "a", criando uma nova matriz e aplicará essa nova como uma base para a outra mostrar os resultados. Como vimos, essa funcionalidade é essencial no conjunto da Pandas, que é o centro deste curso. Por isso, nós o usaremos bastante.**Indexação Booleana**

In [ ]:
print (a > 5)
print(a[a>5])

[[False False]
 [False False]
 [False  True]]
[6]


**Slicing**

Vamos ao Slicing, que é uma maneira de "cortar" um Array menor de outro maior. Para uma dimensão, esse processo é semelhante ao aplicado nas listas. Usaremos os dois pontos (:) para isso. Por exemplo, se colocarmos ":3" nos indicadores de índice "[]", nós obtemos os elementos do índice zero até o 3. Lembrando que o índice 3 é excluído. Criaremos para visualizarmos um array, de 0 a 5. 6 números. Depois, vamos visualizar: print( a [ :3 ] ) Tendo assim os três primeiros elementos. Se colocarmos [2:4], veremos do segundo elemento ao quarto. Mas, novamente, excluindo o quarto. Então: print( a [ 2 : 4 ] ) Ao invés de ver a distância, vamos ver os elementos entre esses índices. Para matrizes multidimensionais, funciona da mesma forma. Vamos ver um exemplo: a = np.array... Vamos criar uma nova lista. E aqui vamos colocar três listas. Vamos ver a matriz que possui três linhas e quatro colunas. Se colocarmos um argumento em um Array, como a[:2], teremos todos os elementos desde o primeiro (0.º), até os da segunda linha (1.º em ordem). Se adicionarmos outro argumento ao Array, por exemplo, a[:2, 1:3], veremos elementos das duas primeiras linhas, porém restritos aos elementos que são da 2ª e 3ª colunas. Vamos tentar fazer isso: a[:2, 1:3] Então, nós queremos tudo das duas linhas e queremos 1 : 3 (da coluna). Resumindo, em matrizes multidimensionais, o primeiro argumento é para selecionar linhas e o segundo selecionar colunas. É importante perceber que este "corte" em um Array é apenas uma mudança na exibição dos mesmos dados. Isso é realmente importante e é chamado "passagem por referência". Portanto, modificar este sub Array pode modificar o Array original, também. Aqui eu vou mudar o elemento da posição [0,0] que é 2, para 50. Assim veremos que o valor no Array original também mudou para 50. Eu criarei um sub_array e usarei o mesmo processo de antes. sub_array = a[ :2, 1:3 ] Pegamos duas linhas e, depois, "1:3" para selecionarmos as colunas. E mostrarei o valor de sub_array[0, 0]. Então, eu vou estabelecer: sub_array[0, 0] = 50 Eu vou mudar para 50. Então nós vamos mostrar o que esse sub array nos dá. Isso deve ser 50. Mas, então, nós vamos pedir para imprimir o nosso array original. Isso é “a” também. Lembre-se de que aqui, é a[0, 1], porque nós mudamos quais colunas seriam selecionadas para o nosso sub array. Então, quando nós pegamos o nosso sub array e fizemos [1 : 3], nós nos livramos da 0ª coluna, em “a”. Então, a 0ª coluna em sub array é a primeira, ou seja, a coluna 1 em “a”.


In [ ]:
a=np.array([0,1,2,3,4,5])
print(a[:3])

[0 1 2]


In [ ]:
print(a[2:4])

[2 3]


In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
a[:2, 1:3]

array([[2, 3],
       [6, 7]])

In [ ]:
sub_array = a[:2, 1:3]
print("sub array index [0,0] value before change:", sub_array[0,0])
sub_array[0,0] = 50
print("sub array [0,0] value after change:", sub_array[0,0])
print("original array index [0,1] value after change", a[0,1])

sub array index [0,0] value before change: 2
sub array [0,0] value after change: 50
original array index [0,1] value after change 50


**Regex**

são inscritos em uma linguagem de formatação condensada. No geral, você pode pensar nas expressões regulares como padrões de validação que você dá a um processador Regex com alguns dados como base. O processador, em seguida, analisa os dados de origem usando o padrão e retorna pedaços de textos de volta para o cientista de dados ou programador, para uma manipulação posterior. Há realmente três razões principais para você querer fazer isso: Para verificar se um padrão existe dentro de alguns dados; Para obter todas as instâncias de um padrão complexo em alguns dados; Ou para organizá-los usando um padrão, geralmente através do Splitting de strings. Regexes não são comuns, mas eles são uma técnica fundamental para a organização ou "limpeza" dos dados em muitas aplicações em Data Science.

In [ ]:
import re

In [ ]:
#Existem várias funções de processamento e leitura importantes que você pode usar. A primeira, match(), checa por uma correspondência entre strings,
#começando desde o início dela, para assim retornar um dado Booleano. Da mesma forma, search(), verifica se há uma correspondência, retornando um Booleano,
#mas podendo pesquisar em qualquer posição.
text = "This is a good day"

if re.search("good",text):
  print("Wonderful!")
else:
  print("Alas :(")

Wonderful!


In [ ]:
#Mas, além de verificar por condicionais, podemos dividir a string. O trabalho que o Regex faz aqui é chamado "Tokenizing",
#onde a string é separada em substrings baseadas em padrões. Tokenizing é uma atividade principal em processamento de linguagem natural,
#que apesar de não falarmos muito sobre isso aqui, você estudará futuramente. Temos também as funções findall() e split(),
#que vão analisar a string para nós e retornar suas partes.
text ="Amy works diligently. Amy gets good grades. Our student Amy is succesful."

re.split("Amy",text)

['',
 ' works diligently. ',
 ' gets good grades. Our student ',
 ' is succesful.']

In [ ]:
#Para contar quantas vezes Amy aparece no basta usar findall()
re.findall("Amy", text)
#Ok, então nós vimos que Search() procura por algum padrão e retorna um booleano, que Split() usará um padrão para criar uma lista de substrings e que
#Findall() vai procurar um padrão e mostrar todas suas ocorrências. Bem, já sabemos como a API RegEx do Python funciona.

['Amy', 'Amy', 'Amy']

In [ ]:
#Vamos agora falar um pouco sobre padrões complexos. A especificação padrão do Regex define uma linguagem de marcação para descrever padrões no texto.
#Vamos começar com os "Anchors". Anchors especificam o início e/ou fim da string que estamos tentando corresponder.
#O circunflexo ^ significa o começo e o sinal do cifrão $ significa o fim. Se você colocar o circunflexo antes de uma string, significa que os textos que o processador
#Regex procura deve começar com a string que você especificar. Quando é no fim, você tem que colocar o sinal "$" para identificar o final de uma string alvo.
#Isso significa que os textos que o Regex recupera devem terminar com a string que você especificou.
text ="Amy works diligently. Amy gets good grades. Our student Amy is succesful."
re.search("^Amy",text)

<re.Match object; span=(0, 3), match='Amy'>

**Patterns and Character Classes**



In [ ]:
grades="ACAAAABCBCAA"
re.findall("B",grades)
re.findall("[AB]",grades)

['A', 'A', 'A', 'A', 'A', 'B', 'B', 'A', 'A']

In [ ]:
#Isso é chamado de set operator. É possível incluir uma faixa de caracteres, que pode ser ordenado alfanumericamente
#
re.findall("[A][B-C]", grades)

['AC', 'AB']

In [ ]:
#Por exemplo, se eu quiser analisar apenas as notas que não eram A, nós faríamos o re.findall, e depois usaríamos o operador
#Set "[]", onde colocaremos "^A" para ser procurado em notas. Vemos aqui que só temos B e C's. Preste bem atenção nisso, o sinal ^ foi usado anteriormente para ser um
#Anchor que buscaria ao início de uma string. Mas dentro do operador Set, esse sinal e outros caracteres especiais dos quais falaremos, eles perdem seu significado.
#E isso pode ser confuso. O que você acha que seria os resultados se colocarmos um antes e um depois? Faremos para ver, com re.findall,
#igual antes, só que com outro sinal ^ no início, ainda procurando em 'grades'. Foque nisso por um instante,
#veja este resultado e reflita sobre o que acabamos de falar. O que você acha que será? Bem, é uma lista vazia,
#porque o Regex está procurando por qualquer valor no início de uma string que não seja um A e nossa string começa com um A, portanto, nada será encontrado.
#Lembre-se, quando você está usando o Operador Set, você está fazendo uma correspondência baseada em caracteres. Ou seja,
#você está combinando caracteres usando um método OR. Ok, já falamos sobre os Anchors e os padrões de correspondência de início e de fim.
#Também falamos sobre caracteres usados com conjuntos através da notação Set "[]".
re.findall("[^A]",grades)

['C', 'B', 'C', 'B', 'C']

**Quantificadores**

In [ ]:
#Quantificadores são o número de vezes que você quer buscar um padrão correspondido antes de ser contada a correspondência de fato.
#O Quantificador mais básico é expresso por e{m,n}, com m e n entre chaves, onde "e" é a expressão ou caractere que queremos combinar, "m"
#é o número mínimo de vezes que você quer que ele seja combinado, e "n" é o número máximo de vezes que o item pode ser combinado.
#Vamos usar aquelas notas em 'grades' como exemplo. Quantas vezes este estudante esteve em uma sequência só de notas A? Para vermos isso, faremos o re.findall
#onde o caractere que estamos interessados é A, de modo que ele toma o lugar de e, abriremos as chaves, queremos ter pelo menos dois dele,
#de modo que é o nosso m terá o valor 2, e aqui usaremos apenas algum valor grande, tal como o 10, fechando chaves e usando tudo isso para buscar em "grades".
re.findall("A{2,10}",grades)
#Aqui estamos usando o 2 como nosso mínimo e o 10 como nosso máximo. Vemos então que houve duas sequências, um onde o aluno teve quatro A's e um onde ele só tinha dois A's.
#Podemos tentar fazer isso usando valores únicos e apenas repetindo o padrão. Faremos isso com "re.findall" procurando várias letras A maiúsculas e queremos um mínimo/máximo
#de apenas uma letra A inicial, se repetindo para o segundo caractere e sempre procurando em "grades".
#Como você pode ver, isso é diferente do primeiro exemplo. O primeiro padrão está procurando por uma junção de dois A's, com até dez A's seguidos,
#então ele vê quatro A's como uma única sequência. Já o segundo está procurando por apenas dois A's seguidos, então ele vê os quatro A's como duas sequências de dois A's.
#Dizemos que o processador Regex começa no início da string e utiliza variáveis para corresponder aos padrões que ele faz.
#É importante observar que a sintaxe do Quantificador Regex não permite que você se desvie do padrão {m,n}.

['AAAA', 'AA']

In [ ]:
re.findall("A{1,1}A{1,1}",grades)

['AA', 'AA', 'AA']

In [ ]:
re.findall("A{1,10}B{1,10}C{1,10}",grades)

['AAAABC']

In [ ]:
#Bem, isso foi quase um truque, porque incluímos um máximo que foi apenas arbitrariamente grande. Existem três outros
#Quantificadores usados para abreviação que podemos pensar em usar aqui. Um asterisco "*" é usado para combinar 0 ou mais vezes, um ponto de interrogação "?"
#para combinar 0 ou 1 vezes e o sinal de mais "+" para combinar 1 ou mais vezes. Vejamos um exemplo mais complexo. a partir de um texto da Wikipédia.
#Vamos abrir um conjunto de dados chamado ferpa.txt. Este é o artigo da FERPA(Uma lei dos EUA) na Wikipédia como um arquivo.
#Vamos colocá-lo em uma variável chamada "wiki". E vamos visualizar isso na tela. Dando uma olhada neste documento, uma das coisas que notamos é que os
#cabeçalhos todos têm a palavra [edit] e colchete antes dela, ou melhor, colchetes, antes e depois dela, seguido por caracteres '\n' indicando uma nova linha.
#Se quiséssemos obter uma lista de todos os cabeçalhos presentes neste artigo, podemos fazê-lo com re.findall. Usando o re.findall e
#colocando aqui que estamos interessados em todos os caracteres que são minúsculos, de "a-z" minúsculos e "A-Z" maiúsculos.
#Estamos interessados em algo entre 1 e 100 caracteres, contanto que eles sejam seguidos por "[edit\]".
#Infelizmente, não podemos utilizar os colchetes aqui, o que torna tudo um pouco mais bagunçado, mas não queremos atrapalhar a notação Set.
##with open("datasets/ferpa.txt","r") as file:
  ##wiki=file.read()
  ##wiki
#exemplo de texto na aula

FileNotFoundError: ignored

**Grupos**

In [ ]:
#você pode combinar padrões diferentes combinados através dos chamados "Grupos", para, posteriormente, mencionar e utilizá-los como quiser.
#Para agrupar padrões basta usar os parênteses (), o que é realmente bem natural. Vamos então reescrever o re.findall usando grupos.
#Com re.findall e iniciando com o padrão de string e, como o queremos no primeiro grupo, usamos o primeiro parêntese para que seja a primeira parte do nosso padrão:
#um grupo que é qualquer caractere ou espaço de uma palavra, qualquer que seja o número de vezes.
#Enquanto o segundo grupo será apenas esta tag [edit\] que denota ser um cabeçalho.
#Vemos que o módulo Python RE quebra o resultado grupo por grupo, portanto podemos nos referir a eles com números também e ter as combinações que são retornadas.
#Mas, como podemos obter uma lista com os objetos correspondidos? Até agora, nós vimos que a Findall() retorna strings, enquanto a Search() e a Match()
#Então "for item in re.finditer(..." e dentro dela colocaremos o padrão em que estamos interessados. E podemos ver o resultado com "print(item.groups())"
#Ele é usado para ver itens encontrados em cada grupo especificamente, mas estamos repetindo para todos eles com o "for". Como você pode notar,
#o Método ".groups" retorna uma tupla de um grupo. Podemos obter um grupo individual com group("número do grupo"), onde o group(0) são todos os grupos, e o outro
#número é uma parte específica do grupo que estamos interessados.
##re.findall("([\w ]*) (\[edit\])",wiki)


In [ ]:
#for item in re.finditer("([\w ]*) (\[edit\])",wiki):
  #print(item.groups())

**Pandas**

vamos explorar a estrutura 'Series' da biblioteca Pandas. Você deverá saber como armazenar e manipular dados de índice unidimensional no objeto 'Series'. A 'Series' é uma das principais estruturas de dados em Pandas. Podemos pensar nisso como um misto de uma lista e um dicionário. Os itens são guardados em uma ordem, e existem rótulos* que podemos usar para acessá-los. [*NT: títulos das colunas] Uma forma fácil de visualizar isso é como sendo duas colunas de dados. A primeira é o índice especial, muito parecido com chaves em um dicionário, enquanto a segunda é, de fato, o seu dado. É importante observar que a coluna de dados tem um label dela própria e pode ser acessado usando o atributo .name Funciona diferente dos dicionários e é muito útil quando se trata de mesclar várias colunas de dados. Falaremos sobre isso mais adiante. Vamos importar Pandas para começar. Então, codificaremos: import pandas as pd Como você poderia esperar, pode-se criar uma 'series' passando uma lista de valores. Quando você faz isso, o Pandas automaticamente designa um índice começando com zero e nomeia esta série como 'None'.

In [ ]:
import pandas as pd

In [ ]:
students = ['Alice','Jack', 'Molly']
#Agora só chamarmos a função em pandas e passar students
pd.Series(students)

0    Alice
1     Jack
2    Molly
dtype: object

In [ ]:
#O resultado é um objeto Series que está bem renderizado na tela.
#Vemos aqui que o Pandas identificou automaticamente o tipo de dados na Series como objeto e definiu o parâmetro dtype como apropriado.
#Vemos que os valores são indexados com inteiros, começando a partir do zero. Agora não temos que usar Strings.
#Se passarmos uma lista de números inteiros, por exemplo, veremos que o Pandas define o tipo como int64. Por trás disso,
#o Pandas armazena os valores das séries num Array tipificado (typed array) usando a biblioteca NumPy.
#Ela oferece agilidade significativa, quando processamos dados assim, ao invés das listas Python tradicionais. Vamos criar uma lista de números.
numbers = [1,2,3]
#e vira series
pd.Series(numbers)

0    1
1    2
2    3
dtype: int64

In [ ]:
#O mais importante é como NumPy e, portanto, o Pandas, lidam com dados ausentes.
#Em Python, temos o tipo "None", que indica a ausência de dado, mas o que fazemos se quisermos ter uma lista tipificada, como esta no objeto Series? Nos bastidores,
#o Pandas faz algumas conversões de tipos. Se criarmos uma lista de Strings e tivermos um elemento, de tipo None,
#o Pandas o insere como um None e usa o tipo 'object' para armazená-lo no Array.
students = ['Alice','Jack', None]
pd.Series(students)

0    Alice
1     Jack
2     None
dtype: object

In [ ]:
#Se criarmos uma lista de números inteiros (Integer) ou decimais (float) e informarmos o tipo None,
#o Pandas automaticamente converte este em um valor de ponto flutuante especial NaN, que significa 'Não é Número'.
numbers = [1,2,None]
pd.Series(numbers)

0    1.0
1    2.0
2    NaN
dtype: float64

In [ ]:
students_scores ={'Alice' : 'Physics',
                  'Jack' : 'Chemistry',
                  'Molly': 'English'}
s = pd.Series(students_scores)
s

Alice      Physics
Jack     Chemistry
Molly      English
dtype: object

In [ ]:
#lista de tuplas
students = [("Alice","Brown"),("Jack","White"),("Molly","Green")]
pd.Series(students)
#Vimos que cada uma das tuplas foram armazenadas em uma série de objetos, no tipo objeto.

0    (Alice, Brown)
1     (Jack, White)
2    (Molly, Green)
dtype: object

In [ ]:
#Você pode também separar a sua criação de índice a partir dos dados, passando o índice como uma lista explícita à série.
s = pd.Series(['Physics','Chemistry','English'], index=['Alice','Jack','Molly'])
s
# Então, o que acontece se a sua lista de valores no objeto índice não está alinhada com as chaves do seu dicionário ao criar a série? Bem,
#o Pandas vai sobrepor a criação automática para favorecer apenas e todos os valores de índice que você forneceu.

Alice      Physics
Jack     Chemistry
Molly      English
dtype: object

In [ ]:
#As séries são um dos principais tipos de dados da biblioteca de Pandas
#Uma Series do Pandas pode ser consultada pela posição do índice ou pelo rótulo do índice.
#Se você não fornecer um índice para a Series, durante a consulta, as posições no rótulo terão efetivamente os mesmos valores.
#Para consultar, por localização numérica, começando em 0, use o atributo iloc. Para consultar pelo rótulo do índice, você pode usar o atributo loc.
import pandas as pd
students_classes ={'Alice': 'Physics',
                   'Jack': 'Chemistry',
                   'Molly': 'English',
                   'Sam': 'History'}
s = pd.Series(students_classes)
s


Alice      Physics
Jack     Chemistry
Molly      English
Sam        History
dtype: object

In [ ]:
#Então para essa série, se quiser ver a quarta posição de entrada deve se utilizar o iloc.
s.iloc[3]

'History'

In [ ]:
#Se quiser ver a classe Molly, deve se utilizar o loc como atributo e o parametro da Molly
s.loc['Molly']

'English'

In [ ]:
#Mantendo em mente que iloc e loc não são métodos, são atributos. Então não usam paranteses para consulta-los mas sim colchetes e isso é chamado de operador de indexação
#em Python chama get ou set
#Pandas tenta deixar o código um pouco mais legivel e fornece uma espécie de sintaxe inteligente
# se você passar um parâmetro inteiro, o operador se comportará como se você quisesse consultar por meio do atributo iloc.
#Então, fará s[3]. Isso é como se usássemos s.iloc[3]. E se você passar um objeto, ele consultará como se você quisesse usar o rótulo com base no atributo loc.
s[3]

'History'

In [ ]:
s['Molly']
#na verdade, fará a consulta como se nós tivéssemos feito s.loc[‘Molly’].

'English'

In [ ]:
#ntão, o que acontece se o seu índice for, na verdade, uma lista de inteiros?
#Isso é um pouco complicado e o Pandas não pode determinar automaticamente se você pretende consultar por posição de índice ou rótulo de índice.
#Portanto, você precisa ter cuidado ao usar o operador de indexação na própria “Series”.
#A opção mais segura é ser mais explícito e usar diretamente os atributos iloc e loc.
class_code ={99: 'Physics',
             100: 'Chemistry',
             101: 'English',
             102: 'History'}
s = pd.Series(class_code)

In [ ]:
#Uma abordagem programática típica para isso seria iterar todos os itens da Series e chamar a operação de seu interesse.
#Por exemplo, poderíamos criar uma Series de números inteiros representando as notas dos alunos e tentar obter a nota média.
grades = pd.Series([90, 80, 70, 60])
total = 0
for grade in grades:
  total +=grade
print(total/len(grades))

75.0


In [ ]:
#. Isso funciona, mas é lento. Os computadores modernos podem realizar muitas tarefas simultaneamente, especialmente, mas não somente, tarefas que envolvem matemática.
#As bibliotecas Pandas e a NumPy subjacente suportam vários métodos de computação.
#E a vetorização, em particular, funciona com a maioria das funções da biblioteca NumPy, incluindo a função de soma.
#Então, aqui está como realmente escreveríamos o código usando o método de soma NumPy. Primeiro, precisamos importar o módulo NumPy.
import numpy as np
total = np.sum(grades)
print(total/len(grades))

75.0


In [ ]:
numbers = pd.Series(np.random.randint(0,1000,10000))
#Agora vamos olhar os 5 principais itens na série para ter certeza que são randomicos.Pode se fazer isso com head() function
numbers.head()

0    904
1    407
2     29
3    644
4     22
dtype: int64

In [ ]:
len(numbers)

10000

In [ ]:
%%timeit -n 100
total = 0
for number in numbers:
  total+=number
total/len(numbers)

1.15 ms ± 50.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
numbers.head()

0    127
1    969
2    293
3    277
4    710
dtype: int64

In [ ]:
numbers+=2
numbers.head()

0    906
1    409
2     31
3    646
4     24
dtype: int64

In [ ]:
for label, value in numbers.iteritems():
  numbers.set_value(label,value+2)
numbers.head()

<ipython-input-17-43a72d30344f>:1: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for label, value in numbers.iteritems():


AttributeError: ignored

In [ ]:
%%timeit -n 10
s = pd.Series(np.random.randint(0,1000,10000))
s=+2

221 µs ± 56.6 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
s = pd.Series([1,2,3])
s.loc['History'] = 102
s

0            1
1            2
2            3
History    102
dtype: int64

In [ ]:
#Vemos que os tipos de dados mistos ou rótulos de índice não importam para o Pandas, uma vez que ‘História’ não está na lista original de índices,
#s.loc [‘História’] cria, essencialmente, um novo elemento na Series, com o índice chamado ‘História’ e o valor 102.
students_classes = pd.Series({'Alice':'Physiscs',
                              'Jack':'Chemistry',
                              'Molly':'English',
                              'Sam':'History'})
students_classes

Alice     Physiscs
Jack     Chemistry
Molly      English
Sam        History
dtype: object

In [ ]:
kelly_classes =pd.Series(['Philosophy','Arts','Math'], index=['Kelly','Kelly','Kelly'])
kelly_classes

Kelly    Philosophy
Kelly          Arts
Kelly          Math
dtype: object

In [ ]:
all_students_classes = students_classes.append(kelly_classes)
all_students_classes

<ipython-input-23-54bb50da2406>:1: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_students_classes = students_classes.append(kelly_classes)


Alice      Physiscs
Jack      Chemistry
Molly       English
Sam         History
Kelly    Philosophy
Kelly          Arts
Kelly          Math
dtype: object

In [ ]:
#Existem algumas considerações importantes ao usar .append( ). Primeiro, o Pandas pegará a Series e tentará inferir e usar os melhores tipos de dados.
#Neste exemplo, tudo é uma string, então não há problemas aqui. Em segundo lugar, o método append, na verdade, não altera os objetos da Series subjacentes.
#Em vez disso, ele retorna uma nova Series que é composta pelas duas juntas. Na verdade, isso é um padrão comum no Pandas.
#Por padrão, ele retorna um novo objeto, em vez de modificar o original. E é algo que você deve prever. Ao imprimir a Series original, podemos ver que ela não mudou.
#Finalmente, podemos ver que, quando consultamos a Series adicional, referente à Kelly, não obtemos um único valor, mas a própria Series.
#Então, se pegarmos all_student_classes.loc[‘Kelly’], na verdade, temos a própria Series.

**Estrutura de dados de Data Frame**

In [ ]:
#O DataFrame é uma estrutura de dados que é o coração da biblioteca Pandas. É um objeto importante que você usará em análise de dados e em tarefas de filtragem.
#O DataFrame é conceitualmente um objeto bidimensional, onde há um índice e várias colunas de conteúdo, com cada coluna possuindo um rótulo
#De fato, a diferença entre uma coluna e uma linha é apenas uma distinção conceitual e você pode imaginar o DataFrame como um array de dois eixos com rótulos.
import pandas as pd

In [ ]:
record1 = pd.Series({'Name': 'Alice',
                     'Class': 'Physics',
                     'Score': 85})
record2 = pd.Series({'Name': 'Jack',
                     'Class': 'Chemistry',
                     'Score': 82})
record3 = pd.Series({'Name': 'Helen',
                     'Class': 'Biology',
                     'Score': 90})

In [ ]:
#Assim com as funções de série, podemos passar em nossos itens individuais em uma matriz e podemos passar em nosso índice valores como argumentos.
#Então df é um nome comum para um DataFrame é igual a pd.DataFrame
df = pd.DataFrame([record1, record2, record3],
                  index=['school1', 'school2', 'school3'])
df

Name      Class  Score
school1  Alice    Physics     85
school2   Jack  Chemistry     82
school3  Helen    Biology     90

In [ ]:
#Assim com as funções de série, podemos usar a função head() para ver as primeiras linhas do DataFrame,
#incluindo índices de ambos os eixos, e podemos usar isso para verificar as colunas e as linhas com df.head().
df.head()

Name      Class  Score
school1  Alice    Physics     85
school2   Jack  Chemistry     82
school3  Helen    Biology     90

In [ ]:
#Um método alternativo é criando uma lista de dicionários, onde cada dicionário representa uma coluna de dado
students =({'Name': 'Alice',
            'Class':  'Physics',
            'Score': 85},
           {'Name': 'Jack',
            'Class':  'Chemistry',
            'Score':  82},
           {'Name': 'Helen',
            'Class':  'Biology',
            'Score': 90})
df = pd.DataFrame(students, index=['school1','school2','school3'])
df.head()

Name      Class  Score
school1  Alice    Physics     85
school2   Jack  Chemistry     82
school3  Helen    Biology     90

In [ ]:
#Bem semelhante à série, podemos extrair dados usando os atributos "iloc" e "loc".
#Dado que o DataFrame é bidimensional, passando um único valor para o operador de indexação loc iremos retornar uma série se houver apenas uma linha de retorno.
df.loc['school2']

Name          Jack
Class    Chemistry
Score           82
Name: school2, dtype: object

In [ ]:
df.loc['school', 'Name']

NameError: ignored

In [ ]:
df.T
#faz a matriz a partir dos dados

In [ ]:
df.T.loc['Name']
#transpoe a matriz de linhas em colunas nos nomes

**DataFrame Indexing and Loading**

In [ ]:
!cat datasets/Admission_Prediction.csv #exemplo de concatenação cat, o ! faz com que execute o restante da linha em shell

cat: datasets/Admission_Prediction.csv: No such file or directory


In [ ]:
import pandas as pd
df = pd.read_csv('datasets/Admission_Prediction.csv')#abre o arquivo em pandas para leitura

FileNotFoundError: ignored

In [ ]:
df.head()#carrega as primeiras linhas

In [ ]:
# No Pandas, podemos usar a função rename( ). Ela pega um parâmetro chamado “columns” e pedimos para fornecer um dicionário que tenha as chaves do nome da coluna antiga e do valor correspondente ao novo nome. Então, vou criar uma nova variável DataFrame:
 new_df=df.rename(columns={‘GRE Score’ : ‘GRE Score’ , ‘TOEFL Score’ : ‘TOEFL Score’  ‘University Rating’ : ‘University Rating’  ‘SOP’ : ‘Statement of Purpose’ , ‘LOR’ : ‘Letter of Recommendation’ , ‘CGPA’ : ‘CGPA’ , ‘Research’ : ‘Research’ , ‘Chance of Admit’ : ‘Chance of Admit’})
 #[renomeamos apenas o ‘SOP’ e o ‘LOR’] Assim, vamos dar uma olhada nisso:
 new_df.head( )

In [ ]:
df.cols

In [ ]:
cols = list(df.columns)
cols = [x.lower().strip for x in cols]
df.columns = cols
df.head()

**Querying a DataFrame**

In [ ]:
import pandas as pd
df = pd.read_csv('datasets/Admission_Predict.csv', index_col=0)

In [ ]:
#Máscaras Booleanas são criadas aplicando operadores diretamente as séries de pandas ou objetos do Dataframe
admit_mask=df['chance of admit']>0.7
df.where(admit_mask).head()#oculta todo o resto da tabela que não faz parte do boleano ou seja só aparece o que for true
df.where(admit_mask).dropna().head()#tira os NaN
df['chance of admit'].gt(0.7).lt(0.9)

**Indexing Data Frames**

In [ ]:
set_index()# essa função usa uma lista de colunas como parametro e promove tais colunas como indice
#O set_index é um processo destrutivo, e não mantém o indice atual. Se deseja manter a ordenação dos indices é necessário fazer isso manualmente, criando novas colunas e copiando os valore de indices nelas
import pandas as pd
df = pd.read_csv('datasets/Admission_Prodict.csv',index_col=0)
df.head()

In [ ]:
df['Serial Number'] = df.index
df = df.set_index('Chance of Admit')
df.head()

In [ ]:
df = df.reset_index()
df.head()

In [ ]:
df['SUMLEV'].unique() #faz soma de dados(agrupamento)

**Missing Values**

In [ ]:
import pandas as pd
#Podemos usar a função .isnull() para criar uma máscara 'booleana' no nosso DataFrame. Isso transmite efetivamente a função isnull() para todas as células de dados.
#Iremos criar um máscara igual a df.isnull(), lembrando que apenas a função .isnull() foi aplicada em todo o dataframe, obtendo uma máscara que tem o tamanho
#relacionado às dimensões do DataFrame mas esta é uma máscara condicional, e podemos dar uma olhada nas primeiras linhas, usando .head()
#Então isso pode ser útil para o processamento de linhas baseadas em certas colunas de dados.
#Outra operação útil é ser capaz de remover todas as linhas que possuem dados ausentes, para isso, usamos a função dropna( ).
#Então podemos codificar: df.dropna().head(10) Note que as linhas com os índices 2, 3, 7 e 11 foram removidas.
#Uma das funções úteis que o Pandas tem para trabalharmos com dados ausentes é a função chamada fillna().
#Esta função recebe alguns parâmetros. Pode ser passado um valor simples que pode ser um valor escalar para alterar todos os valores ausentes para um dado valor.
#Isso realmente não se aplica neste caso, mas é um caso de uso muito comum. Então, se quiséssemos preencher todos os valores faltantes com zero poderíamos usar fillna.
#Digitamos: df.fillna(0, passamos o parâmetro zero, e passamos também inplace=True para alterarmos o próprio DataFrame df.
#Lembre-se que algumas operações com DataFrames retornam cópias do DataFrame. Isso pode ser determinado conforme o valor informado no parâmetro inplace = True

**Merging DataFrames**

In [ ]:
#Como podemos trazer vários DataFrame objetos juntos, seja por fusão horizontalmente ou por concatenação verticalmente, intersecção em conjuntos é conhecido como junção em banco de dados.
#Exemplo de como fazer merge
import pandas as pd
#primeiro criar os dois dataframes
staff_df = pd.DataFrame([{'Name': 'Kelly',  'Role': 'Director of HR' },
                         {'Name': 'Sally',  'Role': 'Course Liason'},
                         {'Name': 'James',  'Role':  'Grader'}])
#E vamos indexar os staffs por nome
staff_df = staff_df.set_index('Name')
#Agora vamos criar um dataframe de estudantes
student_df = pd.DataFrame([{'Name': 'James',  'School': 'Business'},
                           {'Name': 'Mike', 'School': 'Law'},
                           {'Name': 'Sally',  'School': 'Engineering'}])
#E agora vamos indexar por nome também
student_df = student_df.set_index('Name')
#agora vamos imprimir o que sai do dataframe
print(staff_df.head())
print(student_df.head())

                 Role
Name                 
Kelly  Director of HR
Sally   Course Liason
James          Grader
            School
Name              
James     Business
Mike           Law
Sally  Engineering


In [ ]:
#se quisermos a união desses dfs, chamariamos de mesclagem no DataFrame à esquerda e o DataFrame ligado a combinação certa e reveladora de que a queremos para usar uma junção externa.
#Gostariamos de usar os indices esquerdos e direito como colunas de união.
pd.merge(staff_df, student_df, how='outer', left_index=True, right_index=True)

Role       School
Name                              
James          Grader     Business
Kelly  Director of HR          NaN
Mike              NaN          Law
Sally   Course Liason  Engineering

In [ ]:
#Vemos no DataFrame resultante que o mike não tem uma função e John não tem um curso, essas células estão listadas como valores ausentes
#Se quisermos uma mesclagem que apenas contenham aquelas pessoas que são um aluno e um membro da equipe podemos definir como atributo a ser inserido intenamente
pd.merge(staff_df, student_df, how='inner', left_index=True,  right_index=True)
#Podemos ver que o resultado do DataFrame só tem James e Sally nele. Agora temos apenas dois usos comuns
#quando juntamos DataFrames, em ambos exempols nós podemos chamar de adição. O primeiro é quando nos queremos todos os staff sem considerar se são estudantes ou não.
#É importante notar nessa função que: o primeiro dataframe pe o esquerdo e o segundo é o direito.

Role       School
Name                             
Sally  Course Liason  Engineering
James         Grader     Business

In [ ]:
pd.merge(staff_df,  student_df, how='left', left_index=True, right_index=True)

Role       School
Name                              
Kelly  Director of HR          NaN
Sally   Course Liason  Engineering
James          Grader     Business

import numpy as np
from google.colab import autoviz

def categorical_histogram(df, colname, figscale=1, mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  df.groupby(colname).size().plot(kind='barh', color=sns.palettes.mpl_palette(mpl_palette_name), figsize=(8*figscale, 4.8*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  return autoviz.MplChart.from_current_mpl_state()

chart = categorical_histogram(_df_0, *['Name'], **{})
chart

import numpy as np
from google.colab import autoviz

def categorical_histogram(df, colname, figscale=1, mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  df.groupby(colname).size().plot(kind='barh', color=sns.palettes.mpl_palette(mpl_palette_name), figsize=(8*figscale, 4.8*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  return autoviz.MplChart.from_current_mpl_state()

chart = categorical_histogram(_df_1, *['Role'], **{})
chart

import numpy as np
from google.colab import autoviz

def categorical_histogram(df, colname, figscale=1, mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  df.groupby(colname).size().plot(kind='barh', color=sns.palettes.mpl_palette(mpl_palette_name), figsize=(8*figscale, 4.8*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  return autoviz.MplChart.from_current_mpl_state()

chart = categorical_histogram(_df_2, *['School'], **{})
chart

import numpy as np
from google.colab import autoviz

def heatmap(df, x_colname, y_colname, figscale=1, mpl_palette_name='viridis'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  import pandas as pd
  plt.subplots(figsize=(8 * figscale, 8 * figscale))
  df_2dhist = pd.DataFrame({
      x_label: grp[y_colname].value_counts()
      for x_label, grp in df.groupby(x_colname)
  })
  sns.heatmap(df_2dhist, cmap=mpl_palette_name)
  plt.xlabel(x_colname)
  plt.ylabel(y_colname)
  return autoviz.MplChart.from_current_mpl_state()

chart = heatmap(_df_3, *['Name', 'Role'], **{})
chart

import numpy as np
from google.colab import autoviz

def heatmap(df, x_colname, y_colname, figscale=1, mpl_palette_name='viridis'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  import pandas as pd
  plt.subplots(figsize=(8 * figscale, 8 * figscale))
  df_2dhist = pd.DataFrame({
      x_label: grp[y_colname].value_counts()
      for x_label, grp in df.groupby(x_colname)
  })
  sns.heatmap(df_2dhist, cmap=mpl_palette_name)
  plt.xlabel(x_colname)
  plt.ylabel(y_colname)
  return autoviz.MplChart.from_current_mpl_state()

chart = heatmap(_df_4, *['Role', 'School'], **{})
chart

In [ ]:
pd.merge(staff_df,  student_df, how='right',  left_index=True,  right_index=True)

Role       School
Name                             
James         Grader     Business
Mike             NaN          Law
Sally  Course Liason  Engineering

In [ ]:
#Podemos fazer isso de outra maneira também. O método de mesclagem tem alguns outros parâmetros interessantes
#Primeiro você não precisa usar indices para se juntar, você também pode usar colunas.
#Parametro chamado "on" e, em seguida podemos atribuir uma coluna a ambos os DataFrames.
#Coluna de junção: Primeiro, vamos remover o indice
staff_df = staff_df.reset_index()
student_df = student_df.reset_index()
#Agora mesclar usando o parametro on
pd.merge(staff_df,  student_df, how='right',  on='Name')
#Usando o parâmetro "on" ao invés de index


Name           Role       School
0  James         Grader     Business
1   Mike            NaN          Law
2  Sally  Course Liason  Engineering

In [ ]:
#conflito entre DataFrames
staff_df = pd.DataFrame([{'Name': 'Kelly','Role': 'Director of HR',
                          'Location': 'State Street'},
                         {'Name': 'Sally',  'Role': 'Course Lianson',
                          'Location': 'Washington Avenue'},
                         {'Name': 'James',  'Role': 'Grader',
                          'Location': 'Washington Avenue'}])
student_df = pd.DataFrame([{'Name': 'Mike', 'School': 'Law',
                            'Location': 'Fraternity House#22'},
                           {'Name': 'James',  'School': 'Business',
                            'Location': '1024 Billiard Avenue'},
                           {'Name': 'Sally',  'School': 'Engineering',
                            'Location': '512 Wilson Crescent'}])
#No staff DataFrame, é o escritório onde podemos encontrar os empregados. E nós podemos ver o
#Diretor de HR é na State Street, enquanto dois estudantes estão na Washington Avenue.
#A função merge preserva essas informações, mas adiciona um _x ou _y para ajudar a diferencia-los entre cada
pd.merge(staff_df,student_df,how='left', on='Name')

Name            Role         Location_x       School            Location_y
0  Kelly  Director of HR       State Street          NaN                   NaN
1  Sally  Course Lianson  Washington Avenue  Engineering   512 Wilson Crescent
2  James          Grader  Washington Avenue     Business  1024 Billiard Avenue

In [ ]:
#Antes de pararmos de falar de merging de DataFrames vamos falar sobre multi-indexação e multiplas colunas.
#Exemplo com um novo data de estudantes e staff
import pandas as pd
staff_df = pd.DataFrame([{'First Name': 'Kelly',  'Last Name':  'Desjardins',
                          'Role': 'Director of HR'},
                         {'First Name': 'Sally',  'Last Name':  'Brooks',
                          'Role': 'Course Lianson'},
                         {'First Name': 'James',  'Last Name':  'Wilde',
                          'Role': 'Grader'}])
student_df = pd.DataFrame([{'First Name': 'James',  'Last Name':  'Hammond',
                            'School': 'Bussiness'},
                           {'First Name': 'Mike', 'Last Name':  'Smith',
                            'School': 'Law'},
                           {'First Name': 'Sally',  'Last Name':  'Brooks',
                            'School': 'Engineering'}])
#Como pode ser visto, James Wilde e James Hammond não dão match na mesma chave, desde que tenham sobrenomes diferentes. Então é esperado que em um join interno não sejam incluidos
#no output e apenas Sally Brooks esteja.
pd.merge(staff_df,student_df,how='inner',on=['First Name', 'Last Name'])

First Name Last Name            Role       School
0      Sally    Brooks  Course Lianson  Engineering

**Pandas Idioms**

In [ ]:
#vamos começar trazendo nosso procesamento de bibliotecas de data
import pandas as pd
import numpy as np
#timing functionality from timeit module
import timeit
#ntão, o primeiro idioma do Pandas sobre o qual quero falar é chamado encadeamento de métodos.
#A ideia geral por trás do encadeamento de métodos é que cada método no objeto retorna uma referência a esse objeto.
#A beleza disso é que você pode condensar muitas operações diferentes em um DataFrame, por exemplo, em uma linha ou uma instrução de código, pelo menos.
#Então, aqui está uma forma "pandorável" de escrever código com encadeamento de métodos.

**Group By**

In [ ]:
#A ideia por trás do Groupby é que ele pega um quadro de dados, divide em blocos baseados em algumas chaves-valores, aplica computação nesses blocos, então combina
#esses resultados juntos de volta em outro dataframe. Em pandas isso é conhecido como padrão split-apply-combine.

**Splitting**

In [ ]:
#vamos ver um exemplo
import pandas as pd
import numpy as np
df = pd.read_csv('datasets/census.csv')
#E excluir resumos em nível estadual, que tem o valor menor que 40
df = df[df['SUMLEV']==50]
df.head()

FileNotFoundError: ignored

In [ ]:
#no primeiro exemplo para groupby() queremos usar o dado de censo. Vamos obter uma lista de estados exclusivos, e em seguida
#podemos iterar sobre todos esses estados. Para cada estado, podemos reduzir o quadro de dados e calcular a média.

#Vamos executar essa tarefa três vezes e cronometrá-la. Para isso, vamos usar essa função mágica celular %%timeit


In [ ]:
%%timeit -n 3
for state in df['STNAME'].unique():
  #Vamos usar o NumPy para calcular esse estado específico.
  avg = np.average(df.where(df['STNAME']==state).dropna()['CENSUS2010POP'])
  print('Countries in state' +state +
        'have an average population of '+ str(avg))

In [ ]:
#Agora vamos tentar uma abordagem tentando groupby()

In [ ]:
%%timeit -n 3
#Para esse método,começando dizendo ao Pandas que estamos interessados em agrupar o estado por
#nome. Essa é a nossa divisão.
for group. frame in df.groupby('STNAME'):
  #É notavel que há dois valores que definimos aqui. Na verdade, Groupby retorna uma tupla
  #em que o primeiro valor é o valor da chave pela qual estamos tentando agrupar, neste caso
  #um nome de estado específico. O segundo é o quadro de dados projetados que foi encontrado para esse grupo.
  #Agora incluimos nossa lógica na etapa de aplicação, que é apenas para calcular uma média do
  #Census2010POP
  avg = np.average(frame['CENSU2010POP'])
  print('Countries in state' + group +
        'have an average population of '+ str(avg))
  # Pode fornecer uma função para groupby e usa-lá para segmentar seus dados. Exemplo
  #É importante observar que, para fazer isso, você precisa definir o índice do quadro de dados como a coluna pela qual você deseja agrupar primeiro.
  #Criaremos uma nova função chamada set_batch_number. Se o primeiro número do parâmetro for M maiúsculo, retornaremos um zero. Se for Q maiúsculo, retornaremos um.
  #Caso contrário, devolveremos dois. Em seguida, passaremos essa função para o DataFrame.
  df = df.set_index('STNAME')
  def set_batch_number(item):
    if item[0]<'M':
      return 0

    if item[0]<'Q':
      return 1
    return 2

for group, frame in df.groupby(set_batch_number):
  print('There are +' str(len(frame))+ 'records in group'+ str(group)+ 'for processing')



In [ ]:
#função que gerencia os agrupamentos
def grouping_fun(item):
    #CVerificaremos se a parte review_scores_value do índice. O item está no formato da política de cancelamento e review_scores_value.
    #Então é uma tupla. Se o item sub-um for igual a 10, retornaremos os itens abaixo de zero e 10,0.
    if item[1] == 10.0:
      return(item[0],"10.0")
    else:
      return (item[0],"not 10.0")

for group, frame in df.groupby(by=grouping_fun):
  print(group)

**Aggregation**

In [ ]:
#A etapa de aplicação mais simples é a agregação de dados. Isso usa um método chamado agg no objeto groupby.
#Até agora, nós apenas iteramos o objeto groupby, desempacotando-o em um rótulo, o nome do grupo e um DataFrame.
#Mas com agg, podemos passar um dicionário das colunas que estamos interessados em agregar junto com a função que queremos aplicar.
df=df.reset_index()
#exemplo
df.groupby("cancellation_policy").agg({"review_scores_value":np.average})

In [ ]:
df.groupby("cancellation_policy").agg({"review_scores_value"}:np.nanmean)
#Podemos também estender esse dicionário to aggregate para várias funções ou múltiplas colunas,
df.groupby("cancelation_policy").agg({"review_scores_value":(np.nanmean,np.nanstd),"reviews_per_month":np.nanmean})

**Transformation**

In [ ]:
#A transformação é diferente das agregações. Onde agg retorna um único valor por coluna, ou seja, uma linha por grupo, transform retorna um objeto do mesmo tamanho do grupo.
#Essencialmente, ele transmite a função que você fornece pelo dataframe do grupo, retornando um novo dataframe. Isso facilita bastante a combinação de dados posteriormente.
#Por exemplo, suponha que quiséssemos incluir os valores médios de classificação em um determinado grupo por política de cancelamento, mas preservar as formas do quadro de dados
#para que pudéssemos gerar uma diferença entre uma observação individual e a soma.
#Primeiro, vamos definir um subconjunto das colunas nas quais estamos interessados.
#Aqui, vou criar uma coluna variável e dizer que estamos interessados na política de cancelamento e no valor das pontuações das avaliações,
#o que só torna tudo um pouco mais limpo enquanto eu o digito. Agora vamos transformá-lo. Vou armazenar isso em seu próprio dataframe.
#Exemplo
cols=['cancellation_policy','review_score_value']
#Agora vamos transformar,Irá armazenar no próprio dataframe
transform_df=df[cols].groupby('cancellation_policy').transform(np.nanmean)
transform_df.head()

In [ ]:
transform_df.rename({'review_scores_value':'mean_review_scores'},axis='colums', inplace=True)
df=df.merge(transform_df, left_index=True, right_index=True)
df['mean_diff']=np.absolute(df['review_scores_value']-df['mean_review_scores'])
df['mean_diff'].head()

**Filtering**

In [ ]:
# Portanto, o objeto Group-by também é compatível com a filtragem de grupos.
#Geralmente, você deseja agrupar por alguns recursos, fazer algumas transformações nos grupos e, em seguida, eliminar determinados grupos como parte de sua rotina de limpeza.
#A função de filtro assume uma função que se aplica a cada quadro de dados do grupo e retorna um verdadeiro ou falso, dependendo se esse grupo deve ser incluído nos resultados.
#Por exemplo, se quiséssemos, apenas os grupos que têm uma classificação média acima de nove, incluídos em nossos resultados.
df.groupby('cancellation_policy').filter(lambda x: np.nanmean(x['review_scores_value'])>9.2)
#Observe que os resultados ainda estão indexados, mas que qualquer um dos resultados que estavam no grupo com a pontuação média da revisão menor ou igual a 9,2.
#Não somos copiados por causa de como fizemos nossa projeção.

**Applying**

In [ ]:
#De longe, a operação mais comum que eu invoco em objetos Group-by é a função Apply. #u invoco em objetos Group-by é a função Apply.
#Isso permite que você aplique uma função arbitrária a cada grupo e reúna os resultados de cada aplicação em um único quadro de dados em que o índice é preservado.
#Então, vamos ver um exemplo usando nossos dados do Airbnb.

In [ ]:
df=pd.read_csv("datasets/listing.csv")
df=df([['cancellation_policy','review_scores_value']])
df.head()

In [ ]:
#no código anterior tentamos achar a média do review score a os desvios do grupo, usando dois passos, primeiro transform() no groupby object e então nós transmitimos para criar uma nova coluna

In [ ]:
def calc_mean_review_scores(group):
  avg=np.nanmean(group["review_scores_value"])
  group["review_score_mean"]=np.abs(avg-group["review_scores_value"])
  return group

df.groupby('cancellation_policy').apply(calc_mean_review_scores).head()

**Tipos de Escala e dados**

#Escala de Proporção
Na escala de proporção, as unidades de medida são igualmente espaçadas e operações matemáticas como a subtração, divisão e multiplicação são todas válidas. Bons exemplos de escalas de proporção são altura e peso.
#Escala de Intervalo
Na escala de intervalo, as unidades de medida são igualmente espaçadas, como na escala de proporção. Mas não há ausência clara de valor. Ou seja, não há um verdadeiro zero, e assim operações tais como multiplicação e divisão não são válidas.
Um exemplo da escala de intervalos pode ser a temperatura medida em graus Celsius ou Fahrenheit uma vez que nunca há uma ausência de temperatura, e zero graus é, na verdade, um valor significativo em si. A direção em uma bússola pode ser outro bom exemplo, onde zero graus na bússola não indica uma falta de direção, mas em vez disso, descreve uma direção em si. Para a maior parte do trabalho que você fará com mineração de dados, as diferenças entre intervalos de proporção intervalos de escala, podem não ser claramente visíveis ou importantes para o algoritmo que você aplicará, mas é importante ter uma distinção clara em sua mente ao aplicar testes estatísticos avançados.
#Escala Ordenada
A ordem dos valores é importante, mas a diferença entre os valores não é igualmente espaçada. Exemplo notas em letras como A, A+, quando você compara com um valor percentual, a letra por si só cobre 4% dos graus disponíveis e uma letra com um sinal é usada em apenas 3% das notas disponíveis.
Os dados ordenados são muito comuns em 'aprendizagem de máquina' e podem, algumas vezes, ser um trabalho desafiador.
#Escala Nominal
muitas vezes chamadas dados categóricos. Aqui nomes de times em um esporte podem ser um bom exemplo. Há um limitado número de times, mas mudar a sua ordem ou aplicar funções matemáticas a eles não faz sentido. Valores categóricos são muito comuns e, geralmente, nos referimos a dados categóricos onde há apenas dois valores possíveis, tal como categorias binárias


**Método Astype()**
O método "as" tenta mudar o tipo básico dos seus dados, nesse caso para dados categóricos, podendo mudar posteriormente para dados ordenados aplicando um sinalizador ordinal.

In [ ]:
import pandas as pd
df=pd.DataFrame(['A+','A','A-','B+','B','B-','C+','C','C-','D+','D'],
                index=['excelent','excelent','excelent','good','good','good','ok','ok','ok','poor','poor'],
                columns=['Grades'])
df

Grades
excelent     A+
excelent      A
excelent     A-
good         B+
good          B
good         B-
ok           C+
ok            C
ok           C-
poor         D+
poor          D

In [ ]:
#Agora podemos dizer a pandas que queremos trocar o tipo da categoria, usando astype() function
df['Grades'].astype("category").head()

excelent    A+
excelent     A
excelent    A-
good        B+
good         B
Name: Grades, dtype: category
Categories (11, object): ['A', 'A+', 'A-', 'B', ..., 'C+', 'C-', 'D', 'D+']

In [ ]:
my_categories=pd.CategoricalDtype(categories=['D','D+','C-','C','C+','B-','B','B+','A-','A','A+'],
                                  ordered=True)
grades=df['Grades'].astype(my_categories)
grades.head()

excelent    A+
excelent     A
excelent    A-
good        B+
good         B
Name: Grades, dtype: category
Categories (11, object): ['D' < 'D+' < 'C-' < 'C' ... 'B+' < 'A-' < 'A' < 'A+']

In [ ]:
df[df["Grades"]>"C"]

Grades
ok       C+
ok       C-
poor     D+
poor      D

**Pivot Table**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('datasets/cwurData.csv')
#nesse video foi criado uma função para classificar e separar as melhores universidades do mundo em tier, do 1 ao 100, do 101 ao 200, etc...
def create_category(ranking):
  if (ranking >= 1) & (ranking <= 100):
    return "First Tier Top University"
  elif(ranking >= 101) & (ranking <= 200):
    return "Second Top Tier University"
  elif(ranking >= 201) & (ranking <= 300):
    return "Third Top Tier University"
#Agora podemos aplicar aplicar a uma única coluna para criar uma nova série
df['Rank Level']= df['world_rank'].apply(lambda x: create_category(x))
df.head()

In [ ]:
#Através da função pivot table iremos criar colunas de valores resumidos com novas colunas de comparação contendo dados processados. Queremos comparar rank level por país
#onde se localiza a universidade . Então queremos compará-lo em termos de pontuação geral.
#Para isso, diremos ao Pandas que queremos os valores que estão em 'score', e o indexador será 'country', e iremos obter os níveis do ranking, Rank_level.
#Temos três coisas a verificar. Especificaremos a função de agregação e aqui usaremos a função "mean" da NumPy, para calcular

In [ ]:
df.pivot_table(values='score', index='country', columns='Rank_level', aggfunc=[np.mean]).head()
# As tabelas dinâmicas não são limitadas a uma função que você queira aplicar. Você pode passar um parâmetro nomeado 'aggfunc', que é uma lista das diferentes funções
#a serem aplicadas, e o pandas lhe fornecerá o resultado usando nomes de colunas hierárquicas.

In [ ]:
df.pivot_table(values='score', index='country', columns='Rank_Level', aggfunc=[np.mean, np.max]).head()

In [ ]:
df.pivot_table(values='score', index='country', columns='Rank_Level', aggfunc=[np.mean, np.max],
               margins=True).head()

**Funcionalidade de Data e Hora**

In [ ]:
#O pandas tem 4 classes principais relacionadas ao tempo: Timestamp, DatetimeIndex, Period e PeriodIndex


**Timestamp**
representa uma única data e hora, associa valores com pontos no tempo.
Por exemplo,vamos criar um timestamp com uma string 9//1/2019 as 10:15 AM.

In [ ]:
import pandas as pd
import numpy as np
#Timestamp é intercambiável com o datetime do Python na maioria dos casos.
pd.Timestamp('9/1/2019 10:05AM')

Timestamp('2019-09-01 10:05:00')

In [ ]:
#Também podemos criar um timestamp utilizando múltiplos parâmetros, como ano, mês, hora, data e minutos separadamente.
pd.Timestamp(2023, 12, 20, 0, 0)

Timestamp('2023-12-20 00:00:00')

In [ ]:
#isoweekday() o qual mostra o dia da semana do timestamp. Note que 1 representa Segunda-Feira e 7 representa Domingo.
pd.Timestamp(2023, 12, 20, 0, 0).isoweekday()

3

In [ ]:
#Você também pode extrair especificamente o ano, mês, dia, hora, etc de um timestamp. Nós podemos criar alguns novos timestamp e usá-los apenas adicionando a claúsula .second
pd.Timestamp(2023, 12, 20, 5, 2,23).second

23

**Period**

Supondo que não estivessemos interessados em um ponto específico no tempo, e ao invés, quissesemos um espaço de tempo. É aqui que a classe Period entra em cena.
Period representa um espaço do tempo simples, tipo um dia ou um mês específico.
Então aqui vamos apenas criar um período para o mês de janeiro de 2023.

In [ ]:
pd.Period('1/2023')
#Quando impresso mostra a granulidade M de mês.

Period('2023-01', 'M')

In [ ]:
pd.Period('3/22/2023')
#Objetos Period representam um intervalo de tempo completo que você especificou. A aritmética no Period é muita simples e intuitiva. Por exemplo, se quisermos apenas descobrir
#5 meses após janeiro de 2023. Só adicionarmos +5
pd.Period('1/2023') + 5

Period('2023-06', 'M')

**DatetimeIndex e PeriodIndex**

In [ ]:
#O indice de um timestamp é um DatatimeIndex. É realmente muito útil quando você começa a lidar com dados de séries temporais. Primeiro, criamos nossa série de exemplo
# t1, usaremos a data de 1, 2 e 3 de setembro de 2016. Quando olhamos para a série, cada timestamp é o índice que tem um valor associado com ele, nesse caso, a, b e c.
#Então aqui fazemos pd.Series, para uma lista, abc, então esses são nossos valores de dados. E, em seguida, nossos índices e array ao lado dele. E, nós vamos criar três
#Timestamps. Um será o primeiro dia de setembro, depois o segundo dia de setembro, depois o terceiro dia. Vamos dar uma olhada no que isso cria como uma série.

t1 = pd.Series(list('abc'), [pd.Timestamp('2016-09-01'), pd.Timestamp('2016-09-2'), pd.Timestamp('2016-09-3')])
t1

2016-09-01    a
2016-09-02    b
2016-09-03    c
dtype: object

In [ ]:
#Olhando para o tipo do nosso índice de série, nós iremos ver o que é um DatetimeIndex
type(t1.index)
#Da mesma forma, também podemos criar um índice baseado em período.
t2 = pd.Series(list('def'), [pd.Period('2023-09'), pd.Period('2023-10'), pd.Period('2023-11')])
t2

2023-09    d
2023-10    e
2023-11    f
Freq: M, dtype: object

**Converting to Datetime**

In [ ]:
#Agora veremos como converter, para datetime. Suponha que temos uma lista de datas guardadas em strings e queremos criar um novo dataframe.
d1 = ['2 June 2013', 'Aug 29 2014', '2015-06-26', '7/12/16']

ts3 = pd.DataFrame(np.random.randint(10,100,(4,2)), index=d1,
                   columns=list('ab'))
ts3

a   b
2 June 2013  71  37
Aug 29 2014  78  72
2015-06-26   58  18
7/12/16      34  15

In [ ]:
#Usando pandas to_datetime, pandas tentará converter esse Datatime e colocá-los em um formato padrão, porque isso é horrível de lidar.
ts3.index = pd.to_datetime(ts3.index)
ts3

a   b
2013-06-02  71  37
2014-08-29  78  72
2015-06-26  58  18
2016-07-12  34  15

In [ ]:
#Então to_datetime também tem opção, de alterar a ordem das datas. por exemplo, nós podemos passar no argumento dayfirst = True para receber no formato europeu de data, se
#pensarmos que nossos dados serão nesse formato.
pd.to_datetime('4.7.12', dayfirst=True)

Timestamp('2012-07-04 00:00:00')

**Timedelta**

In [ ]:
#Timedelta são subtrações de datas. E isso não é o mesmo que período, embora se pareça a princípio, mas é conceitualmente muito semelhante. Se por exemplo nós quisermos
#a diferença entre 3 de setembro e 1º de setembro, teremos um Timedelta de dois dias.
pd.Timestamp('9/3/2016')-pd.Timestamp('9/1/2016')

Timedelta('2 days 00:00:00')

In [ ]:
#Aqui podemos ver 12 dias e três horas após
pd.Timestamp('9/2/2023 8:10AM') + pd.Timedelta('12D 3H')

Timestamp('2023-09-14 11:10:00')

**Offset**

In [ ]:
#Offset é semelhante ao timedelta, mas segue regras específicas de duração de calendário. Offset permite flexibilidade em termos de tipos de intervalos
#de tempo, além de dias, semanas, meses etc., também tem coisas como dia útil , último dia do mês, começo do semestre, etc. Então séries temporais
#não muito tradicionais, mas coisas que usamos nos negócios o tempo todo.
pd.Timestamp('9/4/2023').weekday()

0

In [ ]:
pd.Timestamp('9/4/2023') + pd.offsets.Week()

Timestamp('2023-09-11 00:00:00')

In [ ]:
pd.Timestamp('9/4/2023') + pd.offsets.MonthEnd()

Timestamp('2023-09-30 00:00:00')

**Trabalhando com Datas no Dataframe**

In [ ]:
#vamos dar uma olhada em alguns truques para trabalhar com datas em um DataFrame. Suponha que queremos olhar nove medidas, tiradas a cada duas semanas,
#todo domingo, começando em outubro de 2016. Usando a função date_range, podemos criar este DatetimeIndex Em date_range, temos que especificar ou a data inicial ou a final.
#Se não é especificada, por padrão, a data é considerada a data inicial. Temos que pegar o especificado número de períodos, e a frequência.
dates = pd.date_range('10-01-2023', periods=9 , freq='2W-SUN')
dates

DatetimeIndex(['2023-10-01', '2023-10-15', '2023-10-29', '2023-11-12',
               '2023-11-26', '2023-12-10', '2023-12-24', '2024-01-07',
               '2024-01-21'],
              dtype='datetime64[ns]', freq='2W-SUN')

In [ ]:
#Há muitas outras frequências que você pode especificar, por exemplo dia útil
pd.date_range('10-01-2023', periods=9, freq='B')

DatetimeIndex(['2023-10-02', '2023-10-03', '2023-10-04', '2023-10-05',
               '2023-10-06', '2023-10-09', '2023-10-10', '2023-10-11',
               '2023-10-12'],
              dtype='datetime64[ns]', freq='B')

In [ ]:
#outro período é trimestre, definindo o início do trimestre em um mês específico como junho.
pd.date_range('04-01-2023', periods=12, freq='QS-JUN')

DatetimeIndex(['2023-06-01', '2023-09-01', '2023-12-01', '2024-03-01',
               '2024-06-01', '2024-09-01', '2024-12-01', '2025-03-01',
               '2025-06-01', '2025-09-01', '2025-12-01', '2026-03-01'],
              dtype='datetime64[ns]', freq='QS-JUN')

In [ ]:
dates = pd.date_range('10-01-2023', periods=9, freq='2W-SUN')
df = pd.DataFrame({'Count 1': 100 + np.random.randint(-5,10,9).cumsum(),
  'Count 2': 120 + np.random.randint(-5,10,9)}, index=dates)
df

Count 1  Count 2
2023-10-01      100      128
2023-10-15       95      127
2023-10-29       91      124
2023-11-12       89      122
2023-11-26       92      129
2023-12-10       98      116
2023-12-24       93      116
2024-01-07       97      126
2024-01-21      101      122

**Testes estatísticos básicos**

In [ ]:
#Utilizaremos o SciPy para executar o teste t de student, usamos muita estatística de diversas
#formas em ciência de dados, nessa aula focaremos em teste de hipóteses, que é uma atividade
#central na análise de dados, por trás de diversos experimentos.
#O objetivo do teste de hipóteses é determinar, se por exemplo, as duas diferentes condições
#que temos em nosso exérimento resultaram em impactos distintos.
import numpy as np
import pandas as pd
#Agora vamos traze novas bibliotecas do SciPy.
from scipy import stats

In [ ]:
#Scipy é uma coleção interessante de bibliotecas para ciência de dados, Matplotlib é uma biblioteca
#de gŕaficos.
#Quando fazemos um teste de hipóteses temos duas afirmações de interesse. A primeire á nossa
#explicação real, que chamamos de hipótese alternativa, e a segunda é a explicação que temos
#que não é suficiente, e nós a chamamos de hióteses nula.

In [ ]:
#Exemplo
df=pd.read_csv('datasets/grades.csv')
df.head()
#veremos 6 tarefas diferentes(assingnments 1,2,..6), com a nota ("grade") e a data de submissão de cada uma.
print("There are {} rows and {} columns".format(df.shape[0], df.shape[1]))

FileNotFoundError: ignored

In [ ]:
early_finishers=pd.df[pd.to_datatime(df['assignment1_submission'])<'2016']
early_finishers.head()

AttributeError: ignored

In [ ]:
late_finishers=df[~df.index.isin(early_finishers.index)]
late_finishers.head()

NameError: ignored

In [ ]:
#Como visto o objeto DataFrame do pandas tem uma variedade de funções estatísticas associacdas
#se chamar a função de média "mean" diretamente no DataFrame, verá que todas as médias para as
#tarefas foram calculadas.
print(early_finishers['assignment1_grade'].mean())
print(late_finishers['assignment1_grade'].mean())

NameError: ignored

In [ ]:
#Teste T de Student Ele nos permite formular a hipótese alternativa
#de que as médias são diferentes, e também a hipótese nula
#de que as médias são iguais, e então testar a hipótese nula.
#Quando fazemos um teste de hipóteses,temos que escolher um nível
#de significância como um limite de quão possível estamos dispostos
#a aceitar. Este nível de significância é tipicamente chamado de alfa.
#EXEMPLO: um limite de 0.05 para nosso alfa, que é cinco porcento.
#Usaremos a função ttest_ind(), que realiza um teste t independente.

In [ ]:
from scipy.stats import ttest_ind
ttest_ind(early_finishers['assignment1_grade'], late_finishers['assignment1_grade'])

NameError: ignored

In [ ]:
#Vemos que a possibilidade é 0,18. Isso significa que não podemos rejeitar
#a hipótese nula. A hipótese nula foi que as duas populações eram iguais.
#Não temos certeza o suficiente em nossa evidência porque a probabilidade é
#maior que alfa para chegar a uma conclusão contrária. Isso não significa que
#provamos que as populações são iguais.

In [ ]:
print(ttest_ind(early_finishers['assignment2_grade'], late_finishers['assignment2_grade']))
print(ttest_ind(early_finishers['assignment3_grade'], late_finishers['assignment3_grade']))
print(ttest_ind(early_finishers['assignment4_grade'], late_finishers['assignment4_grade']))
print(ttest_ind(early_finishers['assignment5_grade'], late_finishers['assignment5_grade']))
print(ttest_ind(early_finishers['assignment6_grade'], late_finishers['assignment6_grade']))

In [ ]:
# Ok, parece que com esses dados não temos evidência suficiente para sugerir que as populações são diferentes em relação a nota.
#Vejamos os valores p por um momento, porque eles estão dizendo coisas que podem auxiliar o design do experimento mais tarde.
#Por exemplo, uma das tarefas, assigment3, tem um valor p próximo de 0,1. Isso significa que se aceitarmos um nível de chance similar a 11 porcento
#ele teria sido considerado estatisticamente significante. Como um pesquisador, isso me sugeriria que há um número de coisas aqui que valem a pena
#considerando o que citamos até então. Por exemplo, se tivermos um pequeno número de participante,
#e não é o caso aqui, ou se hovesse algo único sobre como essas tarefas relacionam-se com nosso experimento, qualquer que seja o experimento,
#Agora os valores p foram desconsiderados por serem insuficientes para nos dizer os suficiente sobre as interações que estavam acontecendo, e duas outras técnicas: intervalos
#de confiança e análise bayesiana, são usadas mais regularmente.
#Um problema com o valor p é que à medida que você executa mais testes provavelmente conseguirá um valor que é estatisticamente significante apenas pelo acaso.
#Simulação disso
df1 = pd.DataFrame([np.random.random(100) for x in range(100)])
df1.head()

0         1         2         3         4         5         6   \
0  0.431244  0.345686  0.402483  0.365358  0.564922  0.995945  0.824339   
1  0.345704  0.050329  0.427898  0.452994  0.095724  0.927962  0.161252   
2  0.041294  0.352616  0.345946  0.852082  0.960296  0.551006  0.720175   
3  0.690794  0.957027  0.392174  0.261033  0.888361  0.954714  0.071810   
4  0.978912  0.986383  0.927772  0.208526  0.835729  0.176551  0.207239   

         7         8         9   ...        90        91        92        93  \
0  0.571780  0.157524  0.274210  ...  0.850715  0.928398  0.339333  0.307185   
1  0.250396  0.398579  0.181863  ...  0.759059  0.638498  0.859140  0.920500   
2  0.455473  0.054205  0.559065  ...  0.487145  0.145539  0.983350  0.996661   
3  0.822986  0.075656  0.029808  ...  0.625454  0.716108  0.617303  0.993741   
4  0.773758  0.717605  0.597866  ...  0.150920  0.232143  0.922119  0.272745   

         94        95        96        97        98        99  
0  0.732528  0.192385  0.525004  0.872667  0.562743  0.065292  
1  0.369359  0.208619  0.900888  0.408136  0.776058  0.870883  
2  0.004236  0.357501  0.711053  0.471269  0.599758  0.821724  
3  0.095671  0.266287  0.686039  0.988619  0.723039  0.583826  
4  0.529456  0.851695  0.597970  0.426918  0.774501  0.938532  

[5 rows x 100 columns]

In [ ]:
df2 = pd.DataFrame([np.random.random(100) for x in range(100)])
df2.head()

0         1         2         3         4         5         6   \
0  0.755876  0.895277  0.748934  0.458237  0.833374  0.089652  0.171452   
1  0.888553  0.256172  0.837398  0.284264  0.482068  0.252779  0.060310   
2  0.189784  0.953738  0.616604  0.384448  0.400303  0.107102  0.968344   
3  0.793176  0.996126  0.169423  0.683355  0.162412  0.417092  0.998659   
4  0.160366  0.958534  0.917105  0.179201  0.726939  0.029018  0.254611   

         7         8         9   ...        90        91        92        93  \
0  0.774501  0.165159  0.297382  ...  0.065858  0.246791  0.034827  0.740935   
1  0.841739  0.283860  0.060820  ...  0.189565  0.484960  0.015685  0.588282   
2  0.643219  0.519223  0.310957  ...  0.162840  0.586053  0.585662  0.065050   
3  0.056808  0.250370  0.857956  ...  0.538474  0.766832  0.648073  0.556135   
4  0.141985  0.869254  0.888679  ...  0.190980  0.292410  0.786402  0.167445   

         94        95        96        97        98        99  
0  0.853231  0.267902  0.859141  0.515318  0.720448  0.469013  
1  0.630799  0.958658  0.984270  0.324611  0.420622  0.859379  
2  0.664315  0.321239  0.587048  0.484307  0.279848  0.516714  
3  0.902752  0.296164  0.490158  0.286384  0.621834  0.544856  
4  0.882004  0.623039  0.836424  0.305961  0.719255  0.674186  

[5 rows x 100 columns]

In [ ]:
#Digamos que o nosso valor crítico é 0,1: nosso alfa é de 10%. Compararemos cada coluna de df1 com a de mesmo número em df2 e informaremos quando o valor p não for menor que 10%
#O que significa ter evidência suficiente para dizer que as colunas são diferentes.
def test_columns(alpha=0.1):
  num_diff=0
  for col in df1.columns:
    teststat,pval=ttest_ind(df[col],df2[col])
    if pval<=alpha:
      print("Col{} is statistically significantly different at alpha={}, pval={}".format(col,alpha,pval))
      num_diff = num_diff+1
  print("Total number different was{}, wich is {}%".format(num_diff,float(num_diff)/len(df1.columns)*100))
test_columns()

NameError: ignored

In [ ]:
#Teste Final#
import numpy as np

a = np.arange(8)
b = a[4:6]
b[:] = 40
c = a[4] + a[6]

In [ ]:
import re
s = 'ABCAC'
bool(re.match('A', s)) == True

True